/*
Myncer API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the OneWaySync type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &OneWaySync{}

// OneWaySync Representative of source -> destination.
type OneWaySync struct {
	SyncVariant string `json:"syncVariant"`
	Source MusicSource `json:"source"`
	Destination MusicSource `json:"destination"`
}

type _OneWaySync OneWaySync

// NewOneWaySync instantiates a new OneWaySync object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOneWaySync(syncVariant string, source MusicSource, destination MusicSource) *OneWaySync {
	this := OneWaySync{}
	this.SyncVariant = syncVariant
	this.Source = source
	this.Destination = destination
	return &this
}

// NewOneWaySyncWithDefaults instantiates a new OneWaySync object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOneWaySyncWithDefaults() *OneWaySync {
	this := OneWaySync{}
	return &this
}

// GetSyncVariant returns the SyncVariant field value
func (o *OneWaySync) GetSyncVariant() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SyncVariant
}

// GetSyncVariantOk returns a tuple with the SyncVariant field value
// and a boolean to check if the value has been set.
func (o *OneWaySync) GetSyncVariantOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SyncVariant, true
}

// SetSyncVariant sets field value
func (o *OneWaySync) SetSyncVariant(v string) {
	o.SyncVariant = v
}

// GetSource returns the Source field value
func (o *OneWaySync) GetSource() MusicSource {
	if o == nil {
		var ret MusicSource
		return ret
	}

	return o.Source
}

// GetSourceOk returns a tuple with the Source field value
// and a boolean to check if the value has been set.
func (o *OneWaySync) GetSourceOk() (*MusicSource, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Source, true
}

// SetSource sets field value
func (o *OneWaySync) SetSource(v MusicSource) {
	o.Source = v
}

// GetDestination returns the Destination field value
func (o *OneWaySync) GetDestination() MusicSource {
	if o == nil {
		var ret MusicSource
		return ret
	}

	return o.Destination
}

// GetDestinationOk returns a tuple with the Destination field value
// and a boolean to check if the value has been set.
func (o *OneWaySync) GetDestinationOk() (*MusicSource, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Destination, true
}

// SetDestination sets field value
func (o *OneWaySync) SetDestination(v MusicSource) {
	o.Destination = v
}

func (o OneWaySync) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o OneWaySync) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["syncVariant"] = o.SyncVariant
	toSerialize["source"] = o.Source
	toSerialize["destination"] = o.Destination
	return toSerialize, nil
}

func (o *OneWaySync) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"syncVariant",
		"source",
		"destination",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varOneWaySync := _OneWaySync{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varOneWaySync)

	if err != nil {
		return err
	}

	*o = OneWaySync(varOneWaySync)

	return err
}

type NullableOneWaySync struct {
	value *OneWaySync
	isSet bool
}

func (v NullableOneWaySync) Get() *OneWaySync {
	return v.value
}

func (v *NullableOneWaySync) Set(val *OneWaySync) {
	v.value = val
	v.isSet = true
}

func (v NullableOneWaySync) IsSet() bool {
	return v.isSet
}

func (v *NullableOneWaySync) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOneWaySync(val *OneWaySync) *NullableOneWaySync {
	return &NullableOneWaySync{value: val, isSet: true}
}

func (v NullableOneWaySync) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOneWaySync) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


