/*
Myncer API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ListDatasourcesResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ListDatasourcesResponse{}

// ListDatasourcesResponse struct for ListDatasourcesResponse
type ListDatasourcesResponse struct {
	ConnectedDatasources []Datasource `json:"connectedDatasources"`
}

type _ListDatasourcesResponse ListDatasourcesResponse

// NewListDatasourcesResponse instantiates a new ListDatasourcesResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewListDatasourcesResponse(connectedDatasources []Datasource) *ListDatasourcesResponse {
	this := ListDatasourcesResponse{}
	this.ConnectedDatasources = connectedDatasources
	return &this
}

// NewListDatasourcesResponseWithDefaults instantiates a new ListDatasourcesResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewListDatasourcesResponseWithDefaults() *ListDatasourcesResponse {
	this := ListDatasourcesResponse{}
	return &this
}

// GetConnectedDatasources returns the ConnectedDatasources field value
func (o *ListDatasourcesResponse) GetConnectedDatasources() []Datasource {
	if o == nil {
		var ret []Datasource
		return ret
	}

	return o.ConnectedDatasources
}

// GetConnectedDatasourcesOk returns a tuple with the ConnectedDatasources field value
// and a boolean to check if the value has been set.
func (o *ListDatasourcesResponse) GetConnectedDatasourcesOk() ([]Datasource, bool) {
	if o == nil {
		return nil, false
	}
	return o.ConnectedDatasources, true
}

// SetConnectedDatasources sets field value
func (o *ListDatasourcesResponse) SetConnectedDatasources(v []Datasource) {
	o.ConnectedDatasources = v
}

func (o ListDatasourcesResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ListDatasourcesResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["connectedDatasources"] = o.ConnectedDatasources
	return toSerialize, nil
}

func (o *ListDatasourcesResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"connectedDatasources",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varListDatasourcesResponse := _ListDatasourcesResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varListDatasourcesResponse)

	if err != nil {
		return err
	}

	*o = ListDatasourcesResponse(varListDatasourcesResponse)

	return err
}

type NullableListDatasourcesResponse struct {
	value *ListDatasourcesResponse
	isSet bool
}

func (v NullableListDatasourcesResponse) Get() *ListDatasourcesResponse {
	return v.value
}

func (v *NullableListDatasourcesResponse) Set(val *ListDatasourcesResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableListDatasourcesResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableListDatasourcesResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableListDatasourcesResponse(val *ListDatasourcesResponse) *NullableListDatasourcesResponse {
	return &NullableListDatasourcesResponse{value: val, isSet: true}
}

func (v NullableListDatasourcesResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableListDatasourcesResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


