/*
Myncer API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
)

// checks if the UserLoginRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UserLoginRequest{}

// UserLoginRequest struct for UserLoginRequest
type UserLoginRequest struct {
	// Email of the user trying to login.
	Email *string `json:"email,omitempty"`
	// Password of the user.
	Password *string `json:"password,omitempty"`
}

// NewUserLoginRequest instantiates a new UserLoginRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUserLoginRequest() *UserLoginRequest {
	this := UserLoginRequest{}
	return &this
}

// NewUserLoginRequestWithDefaults instantiates a new UserLoginRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUserLoginRequestWithDefaults() *UserLoginRequest {
	this := UserLoginRequest{}
	return &this
}

// GetEmail returns the Email field value if set, zero value otherwise.
func (o *UserLoginRequest) GetEmail() string {
	if o == nil || IsNil(o.Email) {
		var ret string
		return ret
	}
	return *o.Email
}

// GetEmailOk returns a tuple with the Email field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UserLoginRequest) GetEmailOk() (*string, bool) {
	if o == nil || IsNil(o.Email) {
		return nil, false
	}
	return o.Email, true
}

// HasEmail returns a boolean if a field has been set.
func (o *UserLoginRequest) HasEmail() bool {
	if o != nil && !IsNil(o.Email) {
		return true
	}

	return false
}

// SetEmail gets a reference to the given string and assigns it to the Email field.
func (o *UserLoginRequest) SetEmail(v string) {
	o.Email = &v
}

// GetPassword returns the Password field value if set, zero value otherwise.
func (o *UserLoginRequest) GetPassword() string {
	if o == nil || IsNil(o.Password) {
		var ret string
		return ret
	}
	return *o.Password
}

// GetPasswordOk returns a tuple with the Password field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UserLoginRequest) GetPasswordOk() (*string, bool) {
	if o == nil || IsNil(o.Password) {
		return nil, false
	}
	return o.Password, true
}

// HasPassword returns a boolean if a field has been set.
func (o *UserLoginRequest) HasPassword() bool {
	if o != nil && !IsNil(o.Password) {
		return true
	}

	return false
}

// SetPassword gets a reference to the given string and assigns it to the Password field.
func (o *UserLoginRequest) SetPassword(v string) {
	o.Password = &v
}

func (o UserLoginRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UserLoginRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Email) {
		toSerialize["email"] = o.Email
	}
	if !IsNil(o.Password) {
		toSerialize["password"] = o.Password
	}
	return toSerialize, nil
}

type NullableUserLoginRequest struct {
	value *UserLoginRequest
	isSet bool
}

func (v NullableUserLoginRequest) Get() *UserLoginRequest {
	return v.value
}

func (v *NullableUserLoginRequest) Set(val *UserLoginRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableUserLoginRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableUserLoginRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUserLoginRequest(val *UserLoginRequest) *NullableUserLoginRequest {
	return &NullableUserLoginRequest{value: val, isSet: true}
}

func (v NullableUserLoginRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUserLoginRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


