// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: myncer/user.proto

package myncer_pbconnect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	myncer "github.com/hansbala/myncer/proto/myncer"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// UserServiceName is the fully-qualified name of the UserService service.
	UserServiceName = "myncer.UserService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// UserServiceCreateUserProcedure is the fully-qualified name of the UserService's CreateUser RPC.
	UserServiceCreateUserProcedure = "/myncer.UserService/CreateUser"
	// UserServiceLoginUserProcedure is the fully-qualified name of the UserService's LoginUser RPC.
	UserServiceLoginUserProcedure = "/myncer.UserService/LoginUser"
	// UserServiceLogoutUserProcedure is the fully-qualified name of the UserService's LogoutUser RPC.
	UserServiceLogoutUserProcedure = "/myncer.UserService/LogoutUser"
	// UserServiceEditUserProcedure is the fully-qualified name of the UserService's EditUser RPC.
	UserServiceEditUserProcedure = "/myncer.UserService/EditUser"
	// UserServiceGetCurrentUserProcedure is the fully-qualified name of the UserService's
	// GetCurrentUser RPC.
	UserServiceGetCurrentUserProcedure = "/myncer.UserService/GetCurrentUser"
)

// UserServiceClient is a client for the myncer.UserService service.
type UserServiceClient interface {
	CreateUser(context.Context, *connect.Request[myncer.CreateUserRequest]) (*connect.Response[myncer.CreateUserResponse], error)
	LoginUser(context.Context, *connect.Request[myncer.LoginUserRequest]) (*connect.Response[myncer.LoginUserResponse], error)
	LogoutUser(context.Context, *connect.Request[myncer.LogoutUserRequest]) (*connect.Response[myncer.LogoutUserResponse], error)
	EditUser(context.Context, *connect.Request[myncer.EditUserRequest]) (*connect.Response[myncer.EditUserResponse], error)
	GetCurrentUser(context.Context, *connect.Request[myncer.CurrentUserRequest]) (*connect.Response[myncer.CurrentUserResponse], error)
}

// NewUserServiceClient constructs a client for the myncer.UserService service. By default, it uses
// the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and sends
// uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewUserServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) UserServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	userServiceMethods := myncer.File_myncer_user_proto.Services().ByName("UserService").Methods()
	return &userServiceClient{
		createUser: connect.NewClient[myncer.CreateUserRequest, myncer.CreateUserResponse](
			httpClient,
			baseURL+UserServiceCreateUserProcedure,
			connect.WithSchema(userServiceMethods.ByName("CreateUser")),
			connect.WithClientOptions(opts...),
		),
		loginUser: connect.NewClient[myncer.LoginUserRequest, myncer.LoginUserResponse](
			httpClient,
			baseURL+UserServiceLoginUserProcedure,
			connect.WithSchema(userServiceMethods.ByName("LoginUser")),
			connect.WithClientOptions(opts...),
		),
		logoutUser: connect.NewClient[myncer.LogoutUserRequest, myncer.LogoutUserResponse](
			httpClient,
			baseURL+UserServiceLogoutUserProcedure,
			connect.WithSchema(userServiceMethods.ByName("LogoutUser")),
			connect.WithClientOptions(opts...),
		),
		editUser: connect.NewClient[myncer.EditUserRequest, myncer.EditUserResponse](
			httpClient,
			baseURL+UserServiceEditUserProcedure,
			connect.WithSchema(userServiceMethods.ByName("EditUser")),
			connect.WithClientOptions(opts...),
		),
		getCurrentUser: connect.NewClient[myncer.CurrentUserRequest, myncer.CurrentUserResponse](
			httpClient,
			baseURL+UserServiceGetCurrentUserProcedure,
			connect.WithSchema(userServiceMethods.ByName("GetCurrentUser")),
			connect.WithClientOptions(opts...),
		),
	}
}

// userServiceClient implements UserServiceClient.
type userServiceClient struct {
	createUser     *connect.Client[myncer.CreateUserRequest, myncer.CreateUserResponse]
	loginUser      *connect.Client[myncer.LoginUserRequest, myncer.LoginUserResponse]
	logoutUser     *connect.Client[myncer.LogoutUserRequest, myncer.LogoutUserResponse]
	editUser       *connect.Client[myncer.EditUserRequest, myncer.EditUserResponse]
	getCurrentUser *connect.Client[myncer.CurrentUserRequest, myncer.CurrentUserResponse]
}

// CreateUser calls myncer.UserService.CreateUser.
func (c *userServiceClient) CreateUser(ctx context.Context, req *connect.Request[myncer.CreateUserRequest]) (*connect.Response[myncer.CreateUserResponse], error) {
	return c.createUser.CallUnary(ctx, req)
}

// LoginUser calls myncer.UserService.LoginUser.
func (c *userServiceClient) LoginUser(ctx context.Context, req *connect.Request[myncer.LoginUserRequest]) (*connect.Response[myncer.LoginUserResponse], error) {
	return c.loginUser.CallUnary(ctx, req)
}

// LogoutUser calls myncer.UserService.LogoutUser.
func (c *userServiceClient) LogoutUser(ctx context.Context, req *connect.Request[myncer.LogoutUserRequest]) (*connect.Response[myncer.LogoutUserResponse], error) {
	return c.logoutUser.CallUnary(ctx, req)
}

// EditUser calls myncer.UserService.EditUser.
func (c *userServiceClient) EditUser(ctx context.Context, req *connect.Request[myncer.EditUserRequest]) (*connect.Response[myncer.EditUserResponse], error) {
	return c.editUser.CallUnary(ctx, req)
}

// GetCurrentUser calls myncer.UserService.GetCurrentUser.
func (c *userServiceClient) GetCurrentUser(ctx context.Context, req *connect.Request[myncer.CurrentUserRequest]) (*connect.Response[myncer.CurrentUserResponse], error) {
	return c.getCurrentUser.CallUnary(ctx, req)
}

// UserServiceHandler is an implementation of the myncer.UserService service.
type UserServiceHandler interface {
	CreateUser(context.Context, *connect.Request[myncer.CreateUserRequest]) (*connect.Response[myncer.CreateUserResponse], error)
	LoginUser(context.Context, *connect.Request[myncer.LoginUserRequest]) (*connect.Response[myncer.LoginUserResponse], error)
	LogoutUser(context.Context, *connect.Request[myncer.LogoutUserRequest]) (*connect.Response[myncer.LogoutUserResponse], error)
	EditUser(context.Context, *connect.Request[myncer.EditUserRequest]) (*connect.Response[myncer.EditUserResponse], error)
	GetCurrentUser(context.Context, *connect.Request[myncer.CurrentUserRequest]) (*connect.Response[myncer.CurrentUserResponse], error)
}

// NewUserServiceHandler builds an HTTP handler from the service implementation. It returns the path
// on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewUserServiceHandler(svc UserServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	userServiceMethods := myncer.File_myncer_user_proto.Services().ByName("UserService").Methods()
	userServiceCreateUserHandler := connect.NewUnaryHandler(
		UserServiceCreateUserProcedure,
		svc.CreateUser,
		connect.WithSchema(userServiceMethods.ByName("CreateUser")),
		connect.WithHandlerOptions(opts...),
	)
	userServiceLoginUserHandler := connect.NewUnaryHandler(
		UserServiceLoginUserProcedure,
		svc.LoginUser,
		connect.WithSchema(userServiceMethods.ByName("LoginUser")),
		connect.WithHandlerOptions(opts...),
	)
	userServiceLogoutUserHandler := connect.NewUnaryHandler(
		UserServiceLogoutUserProcedure,
		svc.LogoutUser,
		connect.WithSchema(userServiceMethods.ByName("LogoutUser")),
		connect.WithHandlerOptions(opts...),
	)
	userServiceEditUserHandler := connect.NewUnaryHandler(
		UserServiceEditUserProcedure,
		svc.EditUser,
		connect.WithSchema(userServiceMethods.ByName("EditUser")),
		connect.WithHandlerOptions(opts...),
	)
	userServiceGetCurrentUserHandler := connect.NewUnaryHandler(
		UserServiceGetCurrentUserProcedure,
		svc.GetCurrentUser,
		connect.WithSchema(userServiceMethods.ByName("GetCurrentUser")),
		connect.WithHandlerOptions(opts...),
	)
	return "/myncer.UserService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case UserServiceCreateUserProcedure:
			userServiceCreateUserHandler.ServeHTTP(w, r)
		case UserServiceLoginUserProcedure:
			userServiceLoginUserHandler.ServeHTTP(w, r)
		case UserServiceLogoutUserProcedure:
			userServiceLogoutUserHandler.ServeHTTP(w, r)
		case UserServiceEditUserProcedure:
			userServiceEditUserHandler.ServeHTTP(w, r)
		case UserServiceGetCurrentUserProcedure:
			userServiceGetCurrentUserHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedUserServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedUserServiceHandler struct{}

func (UnimplementedUserServiceHandler) CreateUser(context.Context, *connect.Request[myncer.CreateUserRequest]) (*connect.Response[myncer.CreateUserResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("myncer.UserService.CreateUser is not implemented"))
}

func (UnimplementedUserServiceHandler) LoginUser(context.Context, *connect.Request[myncer.LoginUserRequest]) (*connect.Response[myncer.LoginUserResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("myncer.UserService.LoginUser is not implemented"))
}

func (UnimplementedUserServiceHandler) LogoutUser(context.Context, *connect.Request[myncer.LogoutUserRequest]) (*connect.Response[myncer.LogoutUserResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("myncer.UserService.LogoutUser is not implemented"))
}

func (UnimplementedUserServiceHandler) EditUser(context.Context, *connect.Request[myncer.EditUserRequest]) (*connect.Response[myncer.EditUserResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("myncer.UserService.EditUser is not implemented"))
}

func (UnimplementedUserServiceHandler) GetCurrentUser(context.Context, *connect.Request[myncer.CurrentUserRequest]) (*connect.Response[myncer.CurrentUserResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("myncer.UserService.GetCurrentUser is not implemented"))
}
