version: "3.8"

services:
  db:
    build:
      context: ./database
      dockerfile: database.Dockerfile
    container_name: postgres-db-container
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped
  server:
    build:
      context: ./backend
      dockerfile: server.Dockerfile
    ports:
      - "8080:8080"
    restart: unless-stopped
    env_file:
      - ./backend/.env
volumes:
  pgdata:
