/* tslint:disable */
/* eslint-disable */
/**
 * Myncer API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { OneWaySync } from './OneWaySync';
import {
    instanceOfOneWaySync,
    OneWaySyncFromJSON,
    OneWaySyncFromJSONTyped,
    OneWaySyncToJSON,
} from './OneWaySync';

/**
 * @type CreateSyncRequest
 * 
 * @export
 */
export type CreateSyncRequest = { syncVariant: 'ONE_WAY' } & OneWaySync;

export function CreateSyncRequestFromJSON(json: any): CreateSyncRequest {
    return CreateSyncRequestFromJSONTyped(json, false);
}

export function CreateSyncRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateSyncRequest {
    if (json == null) {
        return json;
    }
    switch (json['syncVariant']) {
        case 'ONE_WAY':
            return Object.assign({}, OneWaySyncFromJSONTyped(json, true), { syncVariant: 'ONE_WAY' } as const);
        default:
            throw new Error(`No variant of CreateSyncRequest exists with 'syncVariant=${json['syncVariant']}'`);
    }
}

export function CreateSyncRequestToJSON(json: any): any {
    return CreateSyncRequestToJSONTyped(json, false);
}

export function CreateSyncRequestToJSONTyped(value?: CreateSyncRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }
    switch (value['syncVariant']) {
        case 'ONE_WAY':
            return Object.assign({}, OneWaySyncToJSON(value), { syncVariant: 'ONE_WAY' } as const);
        default:
            throw new Error(`No variant of CreateSyncRequest exists with 'syncVariant=${value['syncVariant']}'`);
    }

}

