/* tslint:disable */
/* eslint-disable */
/**
 * Myncer API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface EditUserRequest
 */
export interface EditUserRequest {
    /**
     * 
     * @type {string}
     * @memberof EditUserRequest
     */
    firstName: string;
    /**
     * 
     * @type {string}
     * @memberof EditUserRequest
     */
    lastName: string;
    /**
     * 
     * @type {string}
     * @memberof EditUserRequest
     */
    email: string;
    /**
     * The plain text password of the user.
     * @type {string}
     * @memberof EditUserRequest
     */
    password: string;
}

/**
 * Check if a given object implements the EditUserRequest interface.
 */
export function instanceOfEditUserRequest(value: object): value is EditUserRequest {
    if (!('firstName' in value) || value['firstName'] === undefined) return false;
    if (!('lastName' in value) || value['lastName'] === undefined) return false;
    if (!('email' in value) || value['email'] === undefined) return false;
    if (!('password' in value) || value['password'] === undefined) return false;
    return true;
}

export function EditUserRequestFromJSON(json: any): EditUserRequest {
    return EditUserRequestFromJSONTyped(json, false);
}

export function EditUserRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): EditUserRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'firstName': json['firstName'],
        'lastName': json['lastName'],
        'email': json['email'],
        'password': json['password'],
    };
}

export function EditUserRequestToJSON(json: any): EditUserRequest {
    return EditUserRequestToJSONTyped(json, false);
}

export function EditUserRequestToJSONTyped(value?: EditUserRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'firstName': value['firstName'],
        'lastName': value['lastName'],
        'email': value['email'],
        'password': value['password'],
    };
}

