/* tslint:disable */
/* eslint-disable */
/**
 * Myncer API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Datasource } from './Datasource';
import {
    DatasourceFromJSON,
    DatasourceFromJSONTyped,
    DatasourceToJSON,
    DatasourceToJSONTyped,
} from './Datasource';

/**
 * 
 * @export
 * @interface MusicSource
 */
export interface MusicSource {
    /**
     * 
     * @type {Datasource}
     * @memberof MusicSource
     */
    datasource: Datasource;
    /**
     * Unique, stable playlist identifier for the datasource.
     * @type {string}
     * @memberof MusicSource
     */
    playlistId: string;
}



/**
 * Check if a given object implements the MusicSource interface.
 */
export function instanceOfMusicSource(value: object): value is MusicSource {
    if (!('datasource' in value) || value['datasource'] === undefined) return false;
    if (!('playlistId' in value) || value['playlistId'] === undefined) return false;
    return true;
}

export function MusicSourceFromJSON(json: any): MusicSource {
    return MusicSourceFromJSONTyped(json, false);
}

export function MusicSourceFromJSONTyped(json: any, ignoreDiscriminator: boolean): MusicSource {
    if (json == null) {
        return json;
    }
    return {
        
        'datasource': DatasourceFromJSON(json['datasource']),
        'playlistId': json['playlistId'],
    };
}

export function MusicSourceToJSON(json: any): MusicSource {
    return MusicSourceToJSONTyped(json, false);
}

export function MusicSourceToJSONTyped(value?: MusicSource | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'datasource': DatasourceToJSON(value['datasource']),
        'playlistId': value['playlistId'],
    };
}

