/* tslint:disable */
/* eslint-disable */
/**
 * Myncer API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { MusicSource } from './MusicSource';
import {
    MusicSourceFromJSON,
    MusicSourceFromJSONTyped,
    MusicSourceToJSON,
    MusicSourceToJSONTyped,
} from './MusicSource';
import type { SyncVariant } from './SyncVariant';
import {
    SyncVariantFromJSON,
    SyncVariantFromJSONTyped,
    SyncVariantToJSON,
    SyncVariantToJSONTyped,
} from './SyncVariant';

/**
 * Representative of source -> destination.
 * @export
 * @interface OneWaySync
 */
export interface OneWaySync {
    /**
     * 
     * @type {SyncVariant}
     * @memberof OneWaySync
     */
    syncVariant: SyncVariant;
    /**
     * 
     * @type {MusicSource}
     * @memberof OneWaySync
     */
    source: MusicSource;
    /**
     * 
     * @type {MusicSource}
     * @memberof OneWaySync
     */
    destination: MusicSource;
    /**
     * Overwrites destination songs. 
     * If a song exists in source but not in destination, 
     * the song will be lost from destination.
     * 
     * @type {boolean}
     * @memberof OneWaySync
     */
    overwriteExisting?: boolean;
}



/**
 * Check if a given object implements the OneWaySync interface.
 */
export function instanceOfOneWaySync(value: object): value is OneWaySync {
    if (!('syncVariant' in value) || value['syncVariant'] === undefined) return false;
    if (!('source' in value) || value['source'] === undefined) return false;
    if (!('destination' in value) || value['destination'] === undefined) return false;
    return true;
}

export function OneWaySyncFromJSON(json: any): OneWaySync {
    return OneWaySyncFromJSONTyped(json, false);
}

export function OneWaySyncFromJSONTyped(json: any, ignoreDiscriminator: boolean): OneWaySync {
    if (json == null) {
        return json;
    }
    return {
        
        'syncVariant': SyncVariantFromJSON(json['syncVariant']),
        'source': MusicSourceFromJSON(json['source']),
        'destination': MusicSourceFromJSON(json['destination']),
        'overwriteExisting': json['overwriteExisting'] == null ? undefined : json['overwriteExisting'],
    };
}

export function OneWaySyncToJSON(json: any): OneWaySync {
    return OneWaySyncToJSONTyped(json, false);
}

export function OneWaySyncToJSONTyped(value?: OneWaySync | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'syncVariant': SyncVariantToJSON(value['syncVariant']),
        'source': MusicSourceToJSON(value['source']),
        'destination': MusicSourceToJSON(value['destination']),
        'overwriteExisting': value['overwriteExisting'],
    };
}

