/* tslint:disable */
/* eslint-disable */
/**
 * Myncer API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { MusicSource } from './MusicSource';
import {
    MusicSourceFromJSON,
    MusicSourceFromJSONTyped,
    MusicSourceToJSON,
    MusicSourceToJSONTyped,
} from './MusicSource';

/**
 * Representative of source -> destination.
 * @export
 * @interface OneWaySync
 */
export interface OneWaySync {
    /**
     * 
     * @type {string}
     * @memberof OneWaySync
     */
    syncVariant: OneWaySyncSyncVariantEnum;
    /**
     * 
     * @type {MusicSource}
     * @memberof OneWaySync
     */
    source: MusicSource;
    /**
     * 
     * @type {MusicSource}
     * @memberof OneWaySync
     */
    destination: MusicSource;
}


/**
 * @export
 */
export const OneWaySyncSyncVariantEnum = {
    OneWay: 'ONE_WAY'
} as const;
export type OneWaySyncSyncVariantEnum = typeof OneWaySyncSyncVariantEnum[keyof typeof OneWaySyncSyncVariantEnum];


/**
 * Check if a given object implements the OneWaySync interface.
 */
export function instanceOfOneWaySync(value: object): value is OneWaySync {
    if (!('syncVariant' in value) || value['syncVariant'] === undefined) return false;
    if (!('source' in value) || value['source'] === undefined) return false;
    if (!('destination' in value) || value['destination'] === undefined) return false;
    return true;
}

export function OneWaySyncFromJSON(json: any): OneWaySync {
    return OneWaySyncFromJSONTyped(json, false);
}

export function OneWaySyncFromJSONTyped(json: any, ignoreDiscriminator: boolean): OneWaySync {
    if (json == null) {
        return json;
    }
    return {
        
        'syncVariant': json['syncVariant'],
        'source': MusicSourceFromJSON(json['source']),
        'destination': MusicSourceFromJSON(json['destination']),
    };
}

export function OneWaySyncToJSON(json: any): OneWaySync {
    return OneWaySyncToJSONTyped(json, false);
}

export function OneWaySyncToJSONTyped(value?: OneWaySync | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'syncVariant': value['syncVariant'],
        'source': MusicSourceToJSON(value['source']),
        'destination': MusicSourceToJSON(value['destination']),
    };
}

