/* tslint:disable */
/* eslint-disable */
/**
 * Myncer API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * The variant type of the sync.
 * @export
 */
export const SyncVariant = {
    OneWay: 'ONE_WAY'
} as const;
export type SyncVariant = typeof SyncVariant[keyof typeof SyncVariant];


export function instanceOfSyncVariant(value: any): boolean {
    for (const key in SyncVariant) {
        if (Object.prototype.hasOwnProperty.call(SyncVariant, key)) {
            if (SyncVariant[key as keyof typeof SyncVariant] === value) {
                return true;
            }
        }
    }
    return false;
}

export function SyncVariantFromJSON(json: any): SyncVariant {
    return SyncVariantFromJSONTyped(json, false);
}

export function SyncVariantFromJSONTyped(json: any, ignoreDiscriminator: boolean): SyncVariant {
    return json as SyncVariant;
}

export function SyncVariantToJSON(value?: SyncVariant | null): any {
    return value as any;
}

export function SyncVariantToJSONTyped(value: any, ignoreDiscriminator: boolean): SyncVariant {
    return value as SyncVariant;
}

