// @generated by protoc-gen-es v2.5.2 with parameter "target=ts"
// @generated from file myncer/datasource.proto (package myncer, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile } from "@bufbuild/protobuf/codegenv2";
import { enumDesc, fileDesc } from "@bufbuild/protobuf/codegenv2";

/**
 * Describes the file myncer/datasource.proto.
 */
export const file_myncer_datasource: GenFile = /*@__PURE__*/
  fileDesc("ChdteW5jZXIvZGF0YXNvdXJjZS5wcm90bxIGbXluY2VyKkIKCkRhdGFzb3VyY2USGgoWREFUQVNPVVJDRV9VTlNQRUNJRklFRBAAEgsKB1NQT1RJRlkQARILCgdZT1VUVUJFEAJCM1oxZ2l0aHViLmNvbS9oYW5zYmFsYS9teW5jZXIvcHJvdG8vbXluY2VyO215bmNlcl9wYmIGcHJvdG8z");

/**
 * @generated from enum myncer.Datasource
 */
export enum Datasource {
  /**
   * @generated from enum value: DATASOURCE_UNSPECIFIED = 0;
   */
  DATASOURCE_UNSPECIFIED = 0,

  /**
   * @generated from enum value: SPOTIFY = 1;
   */
  SPOTIFY = 1,

  /**
   * @generated from enum value: YOUTUBE = 2;
   */
  YOUTUBE = 2,
}

/**
 * Describes the enum myncer.Datasource.
 */
export const DatasourceSchema: GenEnum<Datasource> = /*@__PURE__*/
  enumDesc(file_myncer_datasource, 0);

