// @generated by protoc-gen-connect-query v2.1.0 with parameter "target=ts"
// @generated from file myncer/datasource.proto (package myncer, syntax proto3)
/* eslint-disable */

import { DatasourceService } from "./datasource_pb";

/**
 * @generated from rpc myncer.DatasourceService.ExchangeOAuthCode
 */
export const exchangeOAuthCode = DatasourceService.method.exchangeOAuthCode;

/**
 * @generated from rpc myncer.DatasourceService.ListDatasources
 */
export const listDatasources = DatasourceService.method.listDatasources;

/**
 * @generated from rpc myncer.DatasourceService.ListPlaylists
 */
export const listPlaylists = DatasourceService.method.listPlaylists;

/**
 * @generated from rpc myncer.DatasourceService.GetPlaylistDetails
 */
export const getPlaylistDetails = DatasourceService.method.getPlaylistDetails;
