// @generated by protoc-gen-es v2.5.2 with parameter "target=ts"
// @generated from file myncer/oauth_token.proto (package myncer, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Timestamp } from "@bufbuild/protobuf/wkt";
import { file_google_protobuf_timestamp } from "@bufbuild/protobuf/wkt";
import type { Datasource } from "./datasource_pb";
import { file_myncer_datasource } from "./datasource_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file myncer/oauth_token.proto.
 */
export const file_myncer_oauth_token: GenFile = /*@__PURE__*/
  fileDesc("ChhteW5jZXIvb2F1dGhfdG9rZW4ucHJvdG8SBm15bmNlciKoAgoKT0F1dGhUb2tlbhIKCgJpZBgBIAEoCRIPCgd1c2VyX2lkGAIgASgJEhQKDGFjY2Vzc190b2tlbhgDIAEoCRIVCg1yZWZyZXNoX3Rva2VuGAQgASgJEhIKCnRva2VuX3R5cGUYBSABKAkSLgoKZXhwaXJlc19hdBgHIAEoCzIaLmdvb2dsZS5wcm90b2J1Zi5UaW1lc3RhbXASJgoKZGF0YXNvdXJjZRgIIAEoDjISLm15bmNlci5EYXRhc291cmNlEi4KCmNyZWF0ZWRfYXQYCSABKAsyGi5nb29nbGUucHJvdG9idWYuVGltZXN0YW1wEi4KCnVwZGF0ZWRfYXQYCiABKAsyGi5nb29nbGUucHJvdG9idWYuVGltZXN0YW1wSgQIBhAHQjNaMWdpdGh1Yi5jb20vaGFuc2JhbGEvbXluY2VyL3Byb3RvL215bmNlcjtteW5jZXJfcGJiBnByb3RvMw", [file_google_protobuf_timestamp, file_myncer_datasource]);

/**
 * Represents an OAuth token issued by a datasource.
 *
 * @generated from message myncer.OAuthToken
 */
export type OAuthToken = Message<"myncer.OAuthToken"> & {
  /**
   * google/uuid generated UUID.
   *
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * Myncer user id.
   *
   * @generated from field: string user_id = 2;
   */
  userId: string;

  /**
   * @generated from field: string access_token = 3;
   */
  accessToken: string;

  /**
   * @generated from field: string refresh_token = 4;
   */
  refreshToken: string;

  /**
   * @generated from field: string token_type = 5;
   */
  tokenType: string;

  /**
   * @generated from field: google.protobuf.Timestamp expires_at = 7;
   */
  expiresAt?: Timestamp;

  /**
   * @generated from field: myncer.Datasource datasource = 8;
   */
  datasource: Datasource;

  /**
   * Metadata which is fetched from SQL (for it's ACID compliance).
   *
   * @generated from field: google.protobuf.Timestamp created_at = 9;
   */
  createdAt?: Timestamp;

  /**
   * @generated from field: google.protobuf.Timestamp updated_at = 10;
   */
  updatedAt?: Timestamp;
};

/**
 * Describes the message myncer.OAuthToken.
 * Use `create(OAuthTokenSchema)` to create a new message.
 */
export const OAuthTokenSchema: GenMessage<OAuthToken> = /*@__PURE__*/
  messageDesc(file_myncer_oauth_token, 0);

