// @generated by protoc-gen-es v2.5.2 with parameter "target=ts"
// @generated from file myncer/playlist.proto (package myncer, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { MusicSource } from "./sync_pb";
import { file_myncer_sync } from "./sync_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file myncer/playlist.proto.
 */
export const file_myncer_playlist: GenFile = /*@__PURE__*/
  fileDesc("ChVteW5jZXIvcGxheWxpc3QucHJvdG8SBm15bmNlciJrCghQbGF5bGlzdBIpCgxtdXNpY19zb3VyY2UYASABKAsyEy5teW5jZXIuTXVzaWNTb3VyY2USDAoEbmFtZRgCIAEoCRITCgtkZXNjcmlwdGlvbhgDIAEoCRIRCglpbWFnZV91cmwYBCABKAlCM1oxZ2l0aHViLmNvbS9oYW5zYmFsYS9teW5jZXIvcHJvdG8vbXluY2VyO215bmNlcl9wYmIGcHJvdG8z", [file_myncer_sync]);

/**
 * @generated from message myncer.Playlist
 */
export type Playlist = Message<"myncer.Playlist"> & {
  /**
   * @generated from field: myncer.MusicSource music_source = 1;
   */
  musicSource?: MusicSource;

  /**
   * Human readable name of the playlist as stored in the original datasource.
   *
   * @generated from field: string name = 2;
   */
  name: string;

  /**
   * Human readable description of the playlist as stored in the original datasource.
   *
   * @generated from field: string description = 3;
   */
  description: string;

  /**
   * URL to the playlist image as stored in the original datasource.
   *
   * next: 5
   *
   * @generated from field: string image_url = 4;
   */
  imageUrl: string;
};

/**
 * Describes the message myncer.Playlist.
 * Use `create(PlaylistSchema)` to create a new message.
 */
export const PlaylistSchema: GenMessage<Playlist> = /*@__PURE__*/
  messageDesc(file_myncer_playlist, 0);

