// @generated by protoc-gen-es v2.5.2 with parameter "target=ts"
// @generated from file myncer/song.proto (package myncer, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Datasource } from "./datasource_pb";
import { file_myncer_datasource } from "./datasource_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file myncer/song.proto.
 */
export const file_myncer_song: GenFile = /*@__PURE__*/
  fileDesc("ChFteW5jZXIvc29uZy5wcm90bxIGbXluY2VyIo0BCgRTb25nEgoKAmlkGAYgASgJEgwKBG5hbWUYASABKAkSEwoLYXJ0aXN0X25hbWUYAiADKAkSEgoKYWxidW1fbmFtZRgDIAEoCRImCgpkYXRhc291cmNlGAQgASgOMhIubXluY2VyLkRhdGFzb3VyY2USGgoSZGF0YXNvdXJjZV9zb25nX2lkGAUgASgJQjNaMWdpdGh1Yi5jb20vaGFuc2JhbGEvbXluY2VyL3Byb3RvL215bmNlcjtteW5jZXJfcGJiBnByb3RvMw", [file_myncer_datasource]);

/**
 * @generated from message myncer.Song
 */
export type Song = Message<"myncer.Song"> & {
  /**
   * The deterministic, reproducible ID of a bunch of details about the song.
   * In practical terms this is a hash of the song details. See `GetSongId` for impl details.`
   *
   * @generated from field: string id = 6;
   */
  id: string;

  /**
   * @generated from field: string name = 1;
   */
  name: string;

  /**
   * @generated from field: repeated string artist_name = 2;
   */
  artistName: string[];

  /**
   * @generated from field: string album_name = 3;
   */
  albumName: string;

  /**
   * @generated from field: myncer.Datasource datasource = 4;
   */
  datasource: Datasource;

  /**
   * Unique, stable song identifier for the datasource.
   *
   * next: 7
   *
   * @generated from field: string datasource_song_id = 5;
   */
  datasourceSongId: string;
};

/**
 * Describes the message myncer.Song.
 * Use `create(SongSchema)` to create a new message.
 */
export const SongSchema: GenMessage<Song> = /*@__PURE__*/
  messageDesc(file_myncer_song, 0);

