// @generated by protoc-gen-es v2.5.2 with parameter "target=ts"
// @generated from file myncer/sync.proto (package myncer, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { enumDesc, fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import type { Timestamp } from "@bufbuild/protobuf/wkt";
import { file_google_protobuf_timestamp } from "@bufbuild/protobuf/wkt";
import type { MusicSource } from "./datasource_pb";
import { file_myncer_datasource } from "./datasource_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file myncer/sync.proto.
 */
export const file_myncer_sync: GenFile = /*@__PURE__*/
  fileDesc("ChFteW5jZXIvc3luYy5wcm90bxIGbXluY2VyIr8BCgRTeW5jEgoKAmlkGAEgASgJEg8KB3VzZXJfaWQYAiABKAkSLgoKY3JlYXRlZF9hdBgDIAEoCzIaLmdvb2dsZS5wcm90b2J1Zi5UaW1lc3RhbXASLgoKdXBkYXRlZF9hdBgEIAEoCzIaLmdvb2dsZS5wcm90b2J1Zi5UaW1lc3RhbXASKgoMb25lX3dheV9zeW5jGAUgASgLMhIubXluY2VyLk9uZVdheVN5bmNIAEIOCgxzeW5jX3ZhcmlhbnQiswEKB1N5bmNSdW4SDwoHc3luY19pZBgBIAEoCRIOCgZydW5faWQYAiABKAkSJwoLc3luY19zdGF0dXMYAyABKA4yEi5teW5jZXIuU3luY1N0YXR1cxIuCgpjcmVhdGVkX2F0GAQgASgLMhouZ29vZ2xlLnByb3RvYnVmLlRpbWVzdGFtcBIuCgp1cGRhdGVkX2F0GAUgASgLMhouZ29vZ2xlLnByb3RvYnVmLlRpbWVzdGFtcCJ3CgpPbmVXYXlTeW5jEiMKBnNvdXJjZRgBIAEoCzITLm15bmNlci5NdXNpY1NvdXJjZRIoCgtkZXN0aW5hdGlvbhgCIAEoCzITLm15bmNlci5NdXNpY1NvdXJjZRIaChJvdmVyd3JpdGVfZXhpc3RpbmcYAyABKAgiTwoRQ3JlYXRlU3luY1JlcXVlc3QSKgoMb25lX3dheV9zeW5jGAEgASgLMhIubXluY2VyLk9uZVdheVN5bmNIAEIOCgxzeW5jX3ZhcmlhbnQiMAoSQ3JlYXRlU3luY1Jlc3BvbnNlEhoKBHN5bmMYASABKAsyDC5teW5jZXIuU3luYyIkChFEZWxldGVTeW5jUmVxdWVzdBIPCgdzeW5jX2lkGAEgASgJIiUKEkRlbGV0ZVN5bmNSZXNwb25zZRIPCgdzeW5jX2lkGAEgASgJIhIKEExpc3RTeW5jc1JlcXVlc3QiMAoRTGlzdFN5bmNzUmVzcG9uc2USGwoFc3luY3MYASADKAsyDC5teW5jZXIuU3luYyIhCg5SdW5TeW5jUmVxdWVzdBIPCgdzeW5jX2lkGAEgASgJIl0KD1J1blN5bmNSZXNwb25zZRIPCgdzeW5jX2lkGAEgASgJEiIKBnN0YXR1cxgCIAEoDjISLm15bmNlci5TeW5jU3RhdHVzEhUKDWVycm9yX21lc3NhZ2UYAyABKAkqqQEKClN5bmNTdGF0dXMSGwoXU1lOQ19TVEFUVVNfVU5TUEVDSUZJRUQQABIXChNTWU5DX1NUQVRVU19QRU5ESU5HEAESFwoTU1lOQ19TVEFUVVNfUlVOTklORxACEhkKFVNZTkNfU1RBVFVTX0NPTVBMRVRFRBADEhYKElNZTkNfU1RBVFVTX0ZBSUxFRBAEEhkKFVNZTkNfU1RBVFVTX0NBTkNFTExFRBAFMpUCCgtTeW5jU2VydmljZRJDCgpDcmVhdGVTeW5jEhkubXluY2VyLkNyZWF0ZVN5bmNSZXF1ZXN0GhoubXluY2VyLkNyZWF0ZVN5bmNSZXNwb25zZRJDCgpEZWxldGVTeW5jEhkubXluY2VyLkRlbGV0ZVN5bmNSZXF1ZXN0GhoubXluY2VyLkRlbGV0ZVN5bmNSZXNwb25zZRJACglMaXN0U3luY3MSGC5teW5jZXIuTGlzdFN5bmNzUmVxdWVzdBoZLm15bmNlci5MaXN0U3luY3NSZXNwb25zZRI6CgdSdW5TeW5jEhYubXluY2VyLlJ1blN5bmNSZXF1ZXN0GhcubXluY2VyLlJ1blN5bmNSZXNwb25zZUIzWjFnaXRodWIuY29tL2hhbnNiYWxhL215bmNlci9wcm90by9teW5jZXI7bXluY2VyX3BiYgZwcm90bzM", [file_google_protobuf_timestamp, file_myncer_datasource]);

/**
 * @generated from message myncer.Sync
 */
export type Sync = Message<"myncer.Sync"> & {
  /**
   * google/uuid generated UUID.
   *
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * Myncer user id.
   *
   * @generated from field: string user_id = 2;
   */
  userId: string;

  /**
   * Metadata which is fetched from SQL (for it's ACID compliance).
   *
   * @generated from field: google.protobuf.Timestamp created_at = 3;
   */
  createdAt?: Timestamp;

  /**
   * @generated from field: google.protobuf.Timestamp updated_at = 4;
   */
  updatedAt?: Timestamp;

  /**
   * Holds the actual sync data.
   *
   * @generated from oneof myncer.Sync.sync_variant
   */
  syncVariant: {
    /**
     * @generated from field: myncer.OneWaySync one_way_sync = 5;
     */
    value: OneWaySync;
    case: "oneWaySync";
  } | { case: undefined; value?: undefined };
};

/**
 * Describes the message myncer.Sync.
 * Use `create(SyncSchema)` to create a new message.
 */
export const SyncSchema: GenMessage<Sync> = /*@__PURE__*/
  messageDesc(file_myncer_sync, 0);

/**
 * @generated from message myncer.SyncRun
 */
export type SyncRun = Message<"myncer.SyncRun"> & {
  /**
   * The ID of the sync that was run.
   *
   * @generated from field: string sync_id = 1;
   */
  syncId: string;

  /**
   * The run id of this sync.
   * This is expected to be randomly generated for each sync run.
   *
   * @generated from field: string run_id = 2;
   */
  runId: string;

  /**
   * The status of this sync run.
   *
   * @generated from field: myncer.SyncStatus sync_status = 3;
   */
  syncStatus: SyncStatus;

  /**
   * Metadata which is fetched from SQL (for it's ACID compliance).
   *
   * @generated from field: google.protobuf.Timestamp created_at = 4;
   */
  createdAt?: Timestamp;

  /**
   * @generated from field: google.protobuf.Timestamp updated_at = 5;
   */
  updatedAt?: Timestamp;
};

/**
 * Describes the message myncer.SyncRun.
 * Use `create(SyncRunSchema)` to create a new message.
 */
export const SyncRunSchema: GenMessage<SyncRun> = /*@__PURE__*/
  messageDesc(file_myncer_sync, 1);

/**
 * Representative of source -> destination.
 *
 * @generated from message myncer.OneWaySync
 */
export type OneWaySync = Message<"myncer.OneWaySync"> & {
  /**
   * @generated from field: myncer.MusicSource source = 1;
   */
  source?: MusicSource;

  /**
   * @generated from field: myncer.MusicSource destination = 2;
   */
  destination?: MusicSource;

  /**
   * When true, it overwrites the destination songs.
   * If a song exists in source but not in destination, the song will be lost from destination.
   *
   * next: 4
   *
   * @generated from field: bool overwrite_existing = 3;
   */
  overwriteExisting: boolean;
};

/**
 * Describes the message myncer.OneWaySync.
 * Use `create(OneWaySyncSchema)` to create a new message.
 */
export const OneWaySyncSchema: GenMessage<OneWaySync> = /*@__PURE__*/
  messageDesc(file_myncer_sync, 2);

/**
 * @generated from message myncer.CreateSyncRequest
 */
export type CreateSyncRequest = Message<"myncer.CreateSyncRequest"> & {
  /**
   * The sync to create.
   *
   * @generated from oneof myncer.CreateSyncRequest.sync_variant
   */
  syncVariant: {
    /**
     * @generated from field: myncer.OneWaySync one_way_sync = 1;
     */
    value: OneWaySync;
    case: "oneWaySync";
  } | { case: undefined; value?: undefined };
};

/**
 * Describes the message myncer.CreateSyncRequest.
 * Use `create(CreateSyncRequestSchema)` to create a new message.
 */
export const CreateSyncRequestSchema: GenMessage<CreateSyncRequest> = /*@__PURE__*/
  messageDesc(file_myncer_sync, 3);

/**
 * @generated from message myncer.CreateSyncResponse
 */
export type CreateSyncResponse = Message<"myncer.CreateSyncResponse"> & {
  /**
   * The created sync.
   *
   * @generated from field: myncer.Sync sync = 1;
   */
  sync?: Sync;
};

/**
 * Describes the message myncer.CreateSyncResponse.
 * Use `create(CreateSyncResponseSchema)` to create a new message.
 */
export const CreateSyncResponseSchema: GenMessage<CreateSyncResponse> = /*@__PURE__*/
  messageDesc(file_myncer_sync, 4);

/**
 * @generated from message myncer.DeleteSyncRequest
 */
export type DeleteSyncRequest = Message<"myncer.DeleteSyncRequest"> & {
  /**
   * The ID of the sync to delete.
   *
   * @generated from field: string sync_id = 1;
   */
  syncId: string;
};

/**
 * Describes the message myncer.DeleteSyncRequest.
 * Use `create(DeleteSyncRequestSchema)` to create a new message.
 */
export const DeleteSyncRequestSchema: GenMessage<DeleteSyncRequest> = /*@__PURE__*/
  messageDesc(file_myncer_sync, 5);

/**
 * @generated from message myncer.DeleteSyncResponse
 */
export type DeleteSyncResponse = Message<"myncer.DeleteSyncResponse"> & {
  /**
   * The ID of the deleted sync.
   *
   * @generated from field: string sync_id = 1;
   */
  syncId: string;
};

/**
 * Describes the message myncer.DeleteSyncResponse.
 * Use `create(DeleteSyncResponseSchema)` to create a new message.
 */
export const DeleteSyncResponseSchema: GenMessage<DeleteSyncResponse> = /*@__PURE__*/
  messageDesc(file_myncer_sync, 6);

/**
 * @generated from message myncer.ListSyncsRequest
 */
export type ListSyncsRequest = Message<"myncer.ListSyncsRequest"> & {
};

/**
 * Describes the message myncer.ListSyncsRequest.
 * Use `create(ListSyncsRequestSchema)` to create a new message.
 */
export const ListSyncsRequestSchema: GenMessage<ListSyncsRequest> = /*@__PURE__*/
  messageDesc(file_myncer_sync, 7);

/**
 * @generated from message myncer.ListSyncsResponse
 */
export type ListSyncsResponse = Message<"myncer.ListSyncsResponse"> & {
  /**
   * List of syncs for the current user.
   *
   * @generated from field: repeated myncer.Sync syncs = 1;
   */
  syncs: Sync[];
};

/**
 * Describes the message myncer.ListSyncsResponse.
 * Use `create(ListSyncsResponseSchema)` to create a new message.
 */
export const ListSyncsResponseSchema: GenMessage<ListSyncsResponse> = /*@__PURE__*/
  messageDesc(file_myncer_sync, 8);

/**
 * @generated from message myncer.RunSyncRequest
 */
export type RunSyncRequest = Message<"myncer.RunSyncRequest"> & {
  /**
   * The ID of the sync to run.
   *
   * @generated from field: string sync_id = 1;
   */
  syncId: string;
};

/**
 * Describes the message myncer.RunSyncRequest.
 * Use `create(RunSyncRequestSchema)` to create a new message.
 */
export const RunSyncRequestSchema: GenMessage<RunSyncRequest> = /*@__PURE__*/
  messageDesc(file_myncer_sync, 9);

/**
 * @generated from message myncer.RunSyncResponse
 */
export type RunSyncResponse = Message<"myncer.RunSyncResponse"> & {
  /**
   * The ID of the sync that was run.
   *
   * @generated from field: string sync_id = 1;
   */
  syncId: string;

  /**
   * @generated from field: myncer.SyncStatus status = 2;
   */
  status: SyncStatus;

  /**
   * If the sync failed, this will contain the error message.
   *
   * @generated from field: string error_message = 3;
   */
  errorMessage: string;
};

/**
 * Describes the message myncer.RunSyncResponse.
 * Use `create(RunSyncResponseSchema)` to create a new message.
 */
export const RunSyncResponseSchema: GenMessage<RunSyncResponse> = /*@__PURE__*/
  messageDesc(file_myncer_sync, 10);

/**
 * @generated from enum myncer.SyncStatus
 */
export enum SyncStatus {
  /**
   * @generated from enum value: SYNC_STATUS_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * The sync is pending and has not started yet.
   *
   * @generated from enum value: SYNC_STATUS_PENDING = 1;
   */
  PENDING = 1,

  /**
   * The sync is currently running.
   *
   * @generated from enum value: SYNC_STATUS_RUNNING = 2;
   */
  RUNNING = 2,

  /**
   * The sync has completed successfully.
   *
   * @generated from enum value: SYNC_STATUS_COMPLETED = 3;
   */
  COMPLETED = 3,

  /**
   * The sync has failed.
   *
   * @generated from enum value: SYNC_STATUS_FAILED = 4;
   */
  FAILED = 4,

  /**
   * The sync was cancelled.
   *
   * @generated from enum value: SYNC_STATUS_CANCELLED = 5;
   */
  CANCELLED = 5,
}

/**
 * Describes the enum myncer.SyncStatus.
 */
export const SyncStatusSchema: GenEnum<SyncStatus> = /*@__PURE__*/
  enumDesc(file_myncer_sync, 0);

/**
 * @generated from service myncer.SyncService
 */
export const SyncService: GenService<{
  /**
   * @generated from rpc myncer.SyncService.CreateSync
   */
  createSync: {
    methodKind: "unary";
    input: typeof CreateSyncRequestSchema;
    output: typeof CreateSyncResponseSchema;
  },
  /**
   * @generated from rpc myncer.SyncService.DeleteSync
   */
  deleteSync: {
    methodKind: "unary";
    input: typeof DeleteSyncRequestSchema;
    output: typeof DeleteSyncResponseSchema;
  },
  /**
   * @generated from rpc myncer.SyncService.ListSyncs
   */
  listSyncs: {
    methodKind: "unary";
    input: typeof ListSyncsRequestSchema;
    output: typeof ListSyncsResponseSchema;
  },
  /**
   * @generated from rpc myncer.SyncService.RunSync
   */
  runSync: {
    methodKind: "unary";
    input: typeof RunSyncRequestSchema;
    output: typeof RunSyncResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_myncer_sync, 0);

