// @generated by protoc-gen-connect-query v2.1.0 with parameter "target=ts"
// @generated from file myncer/sync.proto (package myncer, syntax proto3)
/* eslint-disable */

import { SyncService } from "./sync_pb";

/**
 * @generated from rpc myncer.SyncService.CreateSync
 */
export const createSync = SyncService.method.createSync;

/**
 * @generated from rpc myncer.SyncService.DeleteSync
 */
export const deleteSync = SyncService.method.deleteSync;

/**
 * @generated from rpc myncer.SyncService.ListSyncs
 */
export const listSyncs = SyncService.method.listSyncs;

/**
 * @generated from rpc myncer.SyncService.GetSync
 */
export const getSync = SyncService.method.getSync;

/**
 * @generated from rpc myncer.SyncService.RunSync
 */
export const runSync = SyncService.method.runSync;

/**
 * @generated from rpc myncer.SyncService.ListSyncRuns
 */
export const listSyncRuns = SyncService.method.listSyncRuns;
