// @generated by protoc-gen-connect-query v2.1.0 with parameter "target=ts"
// @generated from file myncer/user.proto (package myncer, syntax proto3)
/* eslint-disable */

import { UserService } from "./user_pb";

/**
 * @generated from rpc myncer.UserService.CreateUser
 */
export const createUser = UserService.method.createUser;

/**
 * @generated from rpc myncer.UserService.LoginUser
 */
export const loginUser = UserService.method.loginUser;

/**
 * @generated from rpc myncer.UserService.LogoutUser
 */
export const logoutUser = UserService.method.logoutUser;

/**
 * @generated from rpc myncer.UserService.EditUser
 */
export const editUser = UserService.method.editUser;

/**
 * @generated from rpc myncer.UserService.GetCurrentUser
 */
export const getCurrentUser = UserService.method.getCurrentUser;
