// @generated by protoc-gen-es v2.5.2 with parameter "target=ts"
// @generated from file myncer/user.proto (package myncer, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file myncer/user.proto.
 */
export const file_myncer_user: GenFile = /*@__PURE__*/
  fileDesc("ChFteW5jZXIvdXNlci5wcm90bxIGbXluY2VyImEKBFVzZXISCgoCaWQYASABKAkSEgoKZmlyc3RfbmFtZRgCIAEoCRIRCglsYXN0X25hbWUYAyABKAkSDQoFZW1haWwYBCABKAkSFwoPaGFzaGVkX3Bhc3N3b3JkGAUgASgJIiEKEUNyZWF0ZVVzZXJSZXF1ZXN0EgwKBG5hbWUYASABKAkiJgoSQ3JlYXRlVXNlclJlc3BvbnNlEhAKCGdyZWV0aW5nGAEgASgJMlIKC1VzZXJTZXJ2aWNlEkMKCkNyZWF0ZVVzZXISGS5teW5jZXIuQ3JlYXRlVXNlclJlcXVlc3QaGi5teW5jZXIuQ3JlYXRlVXNlclJlc3BvbnNlQjNaMWdpdGh1Yi5jb20vaGFuc2JhbGEvbXluY2VyL3Byb3RvL215bmNlcjtteW5jZXJfcGJiBnByb3RvMw");

/**
 * @generated from message myncer.User
 */
export type User = Message<"myncer.User"> & {
  /**
   * google/uuid generated UUID.
   *
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string first_name = 2;
   */
  firstName: string;

  /**
   * @generated from field: string last_name = 3;
   */
  lastName: string;

  /**
   * @generated from field: string email = 4;
   */
  email: string;

  /**
   * golang.org/x/crypto/bcrypt generated hash of plaintext.
   *
   * @generated from field: string hashed_password = 5;
   */
  hashedPassword: string;
};

/**
 * Describes the message myncer.User.
 * Use `create(UserSchema)` to create a new message.
 */
export const UserSchema: GenMessage<User> = /*@__PURE__*/
  messageDesc(file_myncer_user, 0);

/**
 * @generated from message myncer.CreateUserRequest
 */
export type CreateUserRequest = Message<"myncer.CreateUserRequest"> & {
  /**
   * @generated from field: string name = 1;
   */
  name: string;
};

/**
 * Describes the message myncer.CreateUserRequest.
 * Use `create(CreateUserRequestSchema)` to create a new message.
 */
export const CreateUserRequestSchema: GenMessage<CreateUserRequest> = /*@__PURE__*/
  messageDesc(file_myncer_user, 1);

/**
 * @generated from message myncer.CreateUserResponse
 */
export type CreateUserResponse = Message<"myncer.CreateUserResponse"> & {
  /**
   * @generated from field: string greeting = 1;
   */
  greeting: string;
};

/**
 * Describes the message myncer.CreateUserResponse.
 * Use `create(CreateUserResponseSchema)` to create a new message.
 */
export const CreateUserResponseSchema: GenMessage<CreateUserResponse> = /*@__PURE__*/
  messageDesc(file_myncer_user, 2);

/**
 * @generated from service myncer.UserService
 */
export const UserService: GenService<{
  /**
   * @generated from rpc myncer.UserService.CreateUser
   */
  createUser: {
    methodKind: "unary";
    input: typeof CreateUserRequestSchema;
    output: typeof CreateUserResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_myncer_user, 0);

